#cloud-config
# source: https://thenewstack.io/deploy-a-kubernetes-cluster-on-ubuntu-server-with-microk8s/
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, microk8s
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOH+xaI+RBPwOSfEoCW5RPxumVSYU0iXhmDXnk4ulh210RqXyhN/KspqKIzujPk64HDHO6h90L7W6+VmmURNUACCqJBzLXjF7mEdEODUZ5SXDctbvZC9zEDZgbyBfHhdEIbOpKj/Zzlt8pr/yn5NWgKe9GzxWw/IBkh4wg5Q3zqM8/x3+f5M/Nj62QLMuxU3i0rDQ1ITGPtOZiA9Ea3UU++itSyNziLij+cXRjr9tPUTxVL0NGE/+6K5xEDAxkelB3NlpnLqKmPAr+t4NGE069oYE+nx1LsPhADHoTQYhKUOVcYW+vCXcuJaZlc5paqlaCJFgohq9Mpz41Wl9ZfOeN aws-key
groups:
  - microk8s
system_info:
  default_user:
    groups: [microk8s]
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
  - curl
runcmd:
  - sudo snap install microk8s --classic
  - mkdir /home/ubuntu/.kube